### ISSUE TITLE
Difficulty reviewing /  building

### ISSUE THREAD

**Issue by rbenzazon** [pyoner/svelte-form#32]
Hello,

Thanks a lot for releasing this nice tool. I'm interested in trying it out but I can't find any demo link and I tried to build the App/ project but it won't work, many errors arise and I gave up after solving a couple of them and discovering new ones. 
First, why is this project not working on npm, is it a yarn only project? I had to install yarn to install it.
Then when installing the App/ folder and launching dev or build, many error show that dependencies are missing.

Could you please tell me how to build and test a demo easily?

Best regards

**Comment by pyoner** [comment]
Hello!

Thank you for the report!

I don't have online demo, but I use it in my project https://tsfox.dev

In developing this project I use `pnpm`
To run the app you need to use [pnpm](https://github.com/pnpm/pnpm)

Try clone the repository and run a command:
`pnpm run dev --filter ./packages/app`

I hope this helps you to run the app!

**Comment by rbenzazon** [comment]
Hello,
Thanks for your support ! I tried with pnpm and at least it installed properly but the build is failing when I run dev : 
`bundles src/main.ts → public\bundle.js...
src/App.svelte:3:36 - error TS2307: Cannot find module '@pyoner/svelte-form' or its corresponding type declarations.       

3   import { Form, components } from "@pyoner/svelte-form";
                                     ~~~~~~~~~~~~~~~~~~~~~
src/App.svelte:4:38 - error TS2307: Cannot find module '@pyoner/svelte-form-ajv' or its corresponding type declarations.   

4   import { createAjvValidator } from "@pyoner/svelte-form-ajv";
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~
src/samples/simple.ts:1:23 - error TS2307: Cannot find module '@pyoner/svelte-form' or its corresponding type declarations.

1 import { extra } from "@pyoner/svelte-form";
                        ~~~~~~~~~~~~~~~~~~~~~

node_modules/svelte/types/runtime/ambient.d.ts:2:36 - error TS2300: Duplicate identifier 'default'.

2     export { SvelteComponentDev as default } from 'svelte/internal';
                                     ~~~~~~~

  ../lib/node_modules/svelte/types/runtime/ambient.d.ts:2:36
    2     export { SvelteComponentDev as default } from 'svelte/internal';
                                         ~~~~~~~
    'default' was also declared here.
../lib/node_modules/svelte/types/runtime/ambient.d.ts:2:36 - error TS2300: Duplicate identifier 'default'.

2     export { SvelteComponentDev as default } from 'svelte/internal';
                                     ~~~~~~~

  node_modules/svelte/types/runtime/ambient.d.ts:2:36
    2     export { SvelteComponentDev as default } from 'svelte/internal';
                                         ~~~~~~~
    'default' was also declared here.
../lib/src/components/Form.svelte:4:54 - error TS2307: Cannot find module '@pyoner/svelte-form-common' or its corresponding type declarations.

4   import type { JSONSchema, Errors, Validator } from "@pyoner/svelte-form-common";
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/src/helpers.ts:5:45 - error TS2307: Cannot find module '@pyoner/svelte-form-common' or its corresponding type declarations.

5 import type { JSONObject, JSONSchema } from "@pyoner/svelte-form-common";
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../lib/src/types.ts:2:33 - error TS2307: Cannot find module '@pyoner/svelte-form-common' or its corresponding type declarations.

2 import type { JSONSchema } from "@pyoner/svelte-form-common";
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../lib/src/components/Wrapper.svelte:2:35 - error TS2307: Cannot find module '@pyoner/svelte-form-common' or its corresponding type declarations.

2   import type { JSONSchema } from "@pyoner/svelte-form-common";`

I tried updating svelte / rollup-plugin-svelte but it's only getting worse. 

Could you please indicate me where can I test the json form in https://tsfox.dev/ ?

**Comment by pyoner** [comment]
Sorry, I forgot to say before you run the app, you need to install and build all dependencies packages:
```bash
pnpm i -r
pnpm run build -r
``` 

After that run the app:

```bash
pnpm run dev --filter ./packages/app
```
> Could you please indicate me where can I test the json form in https://tsfox.dev/ ?

Sing up and try [to create an engine](https://tsfox.dev/dashboard/engine/#create)

**Comment by rbenzazon** [comment]
Cool, I managed to build, sorry I'm not familiar with pnmp and this workspace setup.
I tried the samples and the "create an engine" it works well. Now I'm wondering how I would use it in an existing svelte project, as a dependency and how I would skin and customize the behavior. I'm not sure there is an on change event in the form for now.
How it looks now, I would need probably to modify the source directly.

Thanks for your support and contribution.

Best regards

**Comment by pyoner** [comment]
> Cool, I managed to build, sorry I'm not familiar with pnmp and this workspace setup.

It's ok!


> Now I'm wondering how I would use it in an existing svelte project, as a dependency

For your exiting project I would recommend to install these dependencies:
```bash 
npm i @pyoner/svelte-form @pyoner/svelte-form-ajv ajv@^6.12.0
```

And see the example https://github.com/pyoner/svelte-form/blob/master/packages/app/src/App.svelte


>  and how I would skin and customize the behavior.

You can [redefine form components](https://github.com/pyoner/svelte-form/blob/master/packages/app/src/App.svelte#L50) as you wish see the [from components](https://github.com/pyoner/svelte-form/tree/master/packages/lib/src/components) 


>I'm not sure there is an on change event in the form for now.

The form emits two event `reset` and `submit` https://github.com/pyoner/svelte-form/blob/master/packages/lib/src/components/Form.svelte#L59


> How it looks now, I would need probably to modify the source directly.

I don't know your case, but if you need to change a form field (looks, behavior) try to redefine form field component

Thanks!

**Comment by thadk** [comment]
Thanks for explaining. I deployed a [demo](http://thadk.net/svelte-form/) of this repo [with GitHub Actions](https://github.com/thadk/svelte-form/blob/master/.github/workflows/main.yml) to [gh-pages](https://github.com/thadk/svelte-form/tree/gh-pages) at http://thadk.net/svelte-form/

**Comment by pyoner** [comment]
@thadk many thanks!

**Comment by manuganji** [comment]
Hi @pyoner, is there a way to specify the field order on the rendered form? I can't see a prop for it.

**Comment by pyoner** [comment]
> Hi @pyoner, is there a way to specify the field order on the rendered form? I can't see a prop for it.

Hi @manuganji , you can set the order of fields in json schema

**Comment by manuganji** [comment]
No, the spec doesn't have this. You're probably referring to a non-standard implementation. If you're saying you've already implemented it, could you please share an example for how you do it? Let's say for this schema.


```

{
        type: 'object',
        properties: {
               'a': {
                      type: 'string'
               },
               'b': {
                      type: 'number'
              }
       }
}
```

**Comment by pyoner** [comment]
> No, the spec doesn't have this. You're probably referring to a non-standard implementation. If you're saying you've already implemented it, could you please share an example for how you do it? Let's say for this schema.
> 
> 
> ```
> 
> {
>         type: 'object',
>         properties: {
>                'a': {
>                       type: 'string'
>                },
>                'b': {
>                       type: 'number'
>               }
>        }
> }
> ```

Oh, sorry! I mean in what order the fields are defined in the schema, in that order they will be rendered.

'a' will be rendered first, 'b' second

**Comment by manuganji** [comment]
Thank you for the answers, @pyoner! I think the property order is not guaranteed when you leave it to the javascript engine. I'll propose this new feature in a separate issue. If you accept, I can send a pull request. Thank you for your work! :)

**Comment by pyoner** [comment]
> Thank you for the answers, @pyoner! I think the property order is not guaranteed when you leave it to the javascript engine. I'll propose this new feature in a separate issue. If you accept, I can send a pull request. Thank you for your work! :)

@manuganji ok, you can create an issue and we'll discuss your feature there

Many thanks 👍
